apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-c5pp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-c5pp
    app.kubernetes.io/part-of: tkwch-fix-0075-0059-app
  name: devfile-sample-c5pp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-c5pp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-c5pp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0059-tenant/tkwch-fix-0075-0059-app/devfile-sample-c5pp@sha256:f0a8a69109cf15ee9033d5bee056030bd38823bd9bc5fad1f5f8fbb92ee1353a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
